package com.ciphio.vault.ui

internal val AlgorithmsInfo: List<String> = listOf(
    "Ciphio supports three AES block cipher modes to balance usability and security across scenarios.",
    "AES-GCM (Galois/Counter Mode) is the default. It provides authenticated encryption, ensuring both confidentiality and integrity of your data using a 12-byte nonce and a 16-byte authentication tag.",
    "AES-CBC (Cipher Block Chaining) is included for compatibility with legacy systems. It uses PKCS#5 padding and a fresh 16-byte IV per operation. Integrity checks should be handled separately if you choose this mode.",
    "AES-CTR (Counter Mode) turns AES into a stream cipher with a 16-byte nonce. It is fast and avoids padding altogether. Because it lacks built-in authentication, pair it with a signature or MAC when possible.",
    "All modes derive a 256-bit key from your passphrase using PBKDF2 (SHA-256, 100k iterations, 16-byte salt) per encryption event, keeping raw secrets off disk."
)

internal val TermsContent: List<String> = listOf(
    "Ciphio operates entirely on your device. No text, keys, or history items are sent to external servers.",
    "You are responsible for safeguarding the passwords and encrypted outputs generated by this application.",
    "Encryption strength ultimately depends on the complexity of the passphrases you choose. Use long, unique secrets to maximize protection.",
    "By using Ciphio you acknowledge that the developers are not liable for data loss, misuse, or damages arising from the app's use.",
    "The application may evolve over time. Continued use after updates constitutes acceptance of any revised terms."
)
